export const FETCH_DASHBOARD = 'FETCH_DASHBOARD';
export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS';
export const FETCH_DASHBOARD_ERROR = 'FETCH_DASHBOARD_ERROR';

export const POST_DASHBOARD = 'POST_DASHBOARD';
export const POST_DASHBOARD_SUCCESS = 'POST_DASHBOARD_SUCCESS';
export const POST_DASHBOARD_ERROR = 'POST_DASHBOARD_ERROR';

export const FETCH_DASHBOARD_OPTIONS = 'FETCH_DASHBOARD_OPTIONS';
export const FETCH_DASHBOARD_OPTIONS_SUCCESS = 'FETCH_DASHBOARD_OPTIONS_SUCCESS';
export const FETCH_DASHBOARD_OPTIONS_ERROR = 'FETCH_DASHBOARD_OPTIONS_ERROR';