export const FETCH_SIDE_MENU_OPTIONS = 'FETCH_SIDE_MENU_OPTIONS';
export const FETCH_SIDE_MENU_OPTIONS_SUCCESS = 'FETCH_SIDE_MENU_OPTIONS_SUCCESS';
export const FETCH_SIDE_MENU_OPTIONS_ERROR = 'FETCH_SIDE_MENU_OPTIONS_ERROR';

export const FETCH_SIDE_MENU = 'FETCH_SIDE_MENU';
export const FETCH_SIDE_MENU_SUCCESS = 'FETCH_SIDE_MENU_SUCCESS';
export const FETCH_SIDE_MENU_ERROR = 'FETCH_SIDE_MENU_ERROR';

export const POST_SIDE_MENU = 'POST_SIDE_MENU';
export const POST_SIDE_MENU_SUCCESS = 'POST_SIDE_MENU_SUCCESS';
export const POST_SIDE_MENU_ERROR = 'POST_SIDE_MENU_ERROR';