export const FETCH_SIDE_MENU_OPTIONS = 'FETCH_SIDE_MENU_OPTIONS';
export const FETCH_SIDE_MENU_OPTIONS_SUCCESS = 'FETCH_SIDE_MENU_OPTIONS_SUCCESS';
export const FETCH_SIDE_MENU_OPTIONS_ERROR = 'FETCH_SIDE_MENU_OPTIONS_ERROR';